# Generated by Django 3.1.6 on 2021-04-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('legislatifs', 'Legislatifs'), ('reglementaires', 'Reglementaires'), ('nominations', 'Nominations')], default='legislatifs', max_length=50)),
                ('pdf', models.FileField(upload_to='pdf')),
            ],
        ),
    ]
