# Generated by Django 3.1.6 on 2021-04-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_juridique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='Title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
