# Generated by Django 3.1.6 on 2021-04-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_juridique', '0002_pdf_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='Title',
            new_name='title',
        ),
    ]
