# Generated by Django 3.1.6 on 2021-03-21 15:14

import TDS.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDS', '0007_auto_20210321_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableau_de_synthese',
            name='year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1998), TDS.models.max_value_current_year]),
        ),
    ]
