# Generated by Django 3.1.7 on 2021-03-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur', models.CharField(max_length=50)),
                ('destinataire', models.CharField(max_length=50)),
                ('date_arrive_depart', models.DateField()),
                ('objet', models.CharField(max_length=1000)),
                ('numero_ordre', models.IntegerField()),
                ('numero_correpondance', models.IntegerField()),
                ('observations', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('types', models.CharField(choices=[('C', 'Cadres'), ('CS', 'Chefs Services'), ('CB', 'Chefs Bureaux'), ('DR', 'Delegue Regional')], max_length=50)),
                ('typess', models.CharField(choices=[('M', 'Mines'), ('AF', 'Affaires Generales'), ('ID', 'Industrie et Developpement Technologique')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transmission', models.DateField()),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier', to='myapp.courier')),
                ('destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinataire', to='myapp.users')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediteur', to='myapp.users')),
            ],
        ),
    ]
