# Generated by Django 3.1.7 on 2021-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mot_de_passe',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('DR', 'Delegue Regional'), ('CB', 'Chefs Bureaux'), ('CS', 'Chefs Services'), ('C', 'Cadres')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('ID', 'Industrie et Developpement Technologique'), ('M', 'Mines'), ('AF', 'Affaires Generales')], max_length=50),
        ),
    ]
