# Generated by Django 3.1.7 on 2021-03-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210323_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='numero_correpondance',
            new_name='numero_correspondance',
        ),
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('CS', 'Chefs Services'), ('C', 'Cadres'), ('CB', 'Chefs Bureaux'), ('DR', 'Delegue Regional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('AF', 'Affaires Generales'), ('ID', 'Industrie et Developpement Technologique'), ('SSD', 'SUPER SAYAN DIVIN'), ('M', 'Mines')], max_length=50),
        ),
    ]
