# Generated by Django 3.1.7 on 2021-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210324_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='types',
            field=models.CharField(choices=[('A', 'Arrive'), ('D', 'Depart')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('CB', 'Chefs Bureaux'), ('CS', 'Chefs Services'), ('C', 'Cadres'), ('DR', 'Delegue Regional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('SSD', 'SUPER SAYAN DIVIN'), ('AF', 'Affaires Generales'), ('ID', 'Industrie et Developpement Technologique'), ('M', 'Mines')], max_length=50),
        ),
    ]
