# Generated by Django 3.1.4 on 2021-03-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210325_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('CS', 'Chefs Services'), ('C', 'Cadres'), ('DR', 'Delegue Regional'), ('CB', 'Chefs Bureaux')], max_length=50),
        ),
    ]
