# Generated by Django 3.1.7 on 2021-03-26 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_auto_20210325_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='observations',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='courier',
            name='types',
            field=models.CharField(choices=[('D', 'Depart'), ('A', 'Arrive')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='date_transmission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='destinataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinataire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='expediteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('DR', 'Delegue Regional'), ('CB', 'Chefs Bureaux'), ('C', 'Cadres'), ('CS', 'Chefs Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('AF', 'Affaires Generales'), ('SSD', 'SUPER SAYAN DIVIN'), ('M', 'Mines'), ('ID', 'Industrie et Developpement Technologique')], max_length=50),
        ),
    ]
