# Generated by Django 3.1.4 on 2021-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210326_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='observations',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('CB', 'Chefs Bureaux'), ('CS', 'Chefs Services'), ('DR', 'Delegue Regional'), ('C', 'Cadres')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('ID', 'Industrie et Developpement Technologique'), ('M', 'Mines'), ('SSD', 'SUPER SAYAN DIVIN'), ('AF', 'Affaires Generales')], max_length=50),
        ),
    ]
