# Generated by Django 3.1.4 on 2021-03-26 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_auto_20210326_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='date_transmission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='destinataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinataire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='expediteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('DR', 'Delegue Regional'), ('C', 'Cadres'), ('CS', 'Chefs Services'), ('CB', 'Chefs Bureaux')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('ID', 'Industrie et Developpement Technologique'), ('AF', 'Affaires Generales'), ('M', 'Mines'), ('SSD', 'SUPER SAYAN DIVIN')], max_length=50),
        ),
    ]
