# Generated by Django 3.1.4 on 2021-04-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210326_0921'),
        ('myapp', '0007_auto_20210326_1613'),
    ]

    operations = [
    ]
