# Generated by Django 3.1.4 on 2021-04-29 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_merge_20210429_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='date_arrive_depart',
        ),
        migrations.AddField(
            model_name='courier',
            name='date_arrive',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='courier',
            name='date_depart',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='courier',
            name='types',
            field=models.CharField(choices=[('A', 'Arrive'), ('D', 'Depart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('CB', 'Chefs Bureaux'), ('C', 'Cadres'), ('DR', 'Delegue Regional'), ('CS', 'Chefs Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('SMGCM', 'Mines Géologie et Cadastre Minier'), ('BRCAM', 'Brigade de Contôle des Activités Minières'), ('SIDTPI', 'Industrie et Developpement Technologique et Propriété Industrielle'), ('SAG', 'Affaires Generales')], max_length=50),
        ),
    ]
