# Generated by Django 3.1.4 on 2021-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210429_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='date_arrive',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='date_depart',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='types',
            field=models.CharField(choices=[('D', 'Depart'), ('A', 'Arrive')], max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('C', 'Cadres'), ('CB', 'Chefs Bureaux'), ('CS', 'Chefs Services'), ('DR', 'Delegue Regional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('SIDTPI', 'Industrie et Developpement Technologique et Propriété Industrielle'), ('SAG', 'Affaires Generales'), ('SMGCM', 'Mines Géologie et Cadastre Minier'), ('BRCAM', 'Brigade de Contôle des Activités Minières')], max_length=50),
        ),
    ]
