# Generated by Django 3.1.4 on 2021-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210429_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='date_arrive',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='courier',
            old_name='date_depart',
            new_name='date_other',
        ),
        migrations.AddField(
            model_name='courier',
            name='isAlsoOther',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courier',
            name='types',
            field=models.CharField(choices=[('D', 'Depart'), ('A', 'Arrive')], max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('SAG', 'Affaires Generales'), ('SIDTPI', 'Industrie et Developpement Technologique et Propriété Industrielle'), ('BRCAM', 'Brigade de Contôle des Activités Minières'), ('SMGCM', 'Mines Géologie et Cadastre Minier')], max_length=50),
        ),
    ]
