# Generated by Django 3.1.4 on 2021-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210429_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='isReceived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('CS', 'Chefs Services'), ('DR', 'Delegue Regional'), ('C', 'Cadres'), ('CB', 'Chefs Bureaux')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='typess',
            field=models.CharField(choices=[('SMGCM', 'Mines Géologie et Cadastre Minier'), ('SIDTPI', 'Industrie et Developpement Technologique et Propriété Industrielle'), ('SAG', 'Affaires Generales'), ('BRCAM', 'Brigade de Contôle des Activités Minières')], max_length=50),
        ),
    ]
