# Generated by Django 3.1.4 on 2021-05-04 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_auto_20210430_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('CSAG', 'Chef Service Affaires Generales'), ('CBDTPI', 'Chef de Bureaux du Developpement Technologique'), ('CBSEI', 'Chef de Bureaux de Suivi des Entreprises Industrielles'), ('CMR1', 'Controleur Miner Régional N1'), ('CBSN', 'Chef de Bureaux de Suivi de la Normalisation'), ('CL', 'Chef de Laboratoire'), ('CSIDTPI', 'Chef Service Industrie et Developpement Technologique et Propriété Industrielle'), ('CBB', 'Chef de Bureaux du Budget'), ('DR', 'Delegue Regional'), ('CSMGCM', 'Chef Service Mines Géologie et Cadastre Minier'), ('CBMG', 'Chef de Bureaux Mine et Geologie'), ('CB', 'Chef de Brigade de Contôle des Activités Minières'), ('CBP', 'Chef de Bureaux du Personnel'), ('CBCM', 'Chef de Bureaux du Cadastre Minier'), ('CMR2', 'Controleur Miner Régional N2'), ('C', 'Cadres'), ('CBC', 'Chef de Bureaux du Courrier')], max_length=50)),
                ('typess', models.CharField(choices=[('SIDTPI', 'Industrie et Developpement Technologique et Propriété Industrielle'), ('BRCAM', 'Brigade de Contôle des Activités Minières'), ('SAG', 'Affaires Generales'), ('SMGCM', 'Mines Géologie et Cadastre Minier')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='courier',
            name='types',
            field=models.CharField(choices=[('A', 'Arrive'), ('D', 'Depart')], max_length=10),
        ),
    ]
