# Generated by Django 3.1.4 on 2021-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210504_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdr',
            name='types',
        ),
        migrations.RemoveField(
            model_name='userdr',
            name='typess',
        ),
        migrations.AddField(
            model_name='userdr',
            name='bureau',
            field=models.CharField(choices=[('BSEI', 'Bureau de Suivi des Entreprises Industrielles')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdr',
            name='poste',
            field=models.CharField(choices=[('CBP', 'Chef de Bureaux du Personnel'), ('C', 'Cadres'), ('CBC', 'Chef de Bureaux du Courrier'), ('CSIDTPI', 'Chef Service Industrie et Developpement Technologique et Propriété Industrielle'), ('CSMGCM', 'Chef Service Mines Géologie et Cadastre Minier'), ('CMR2', 'Controleur Miner Régional N2'), ('CBB', 'Chef de Bureaux du Budget'), ('CBSEI', 'Chef de Bureaux de Suivi des Entreprises Industrielles'), ('CB', 'Chef de Brigade de Contôle des Activités Minières'), ('CBMG', 'Chef de Bureaux Mine et Geologie'), ('CMR1', 'Controleur Miner Régional N1'), ('CL', 'Chef de Laboratoire'), ('DR', 'Delegue Regional'), ('CSAG', 'Chef Service Affaires Generales'), ('CBDTPI', 'Chef de Bureaux du Developpement Technologique'), ('CBCM', 'Chef de Bureaux du Cadastre Minier'), ('CBSN', 'Chef de Bureaux de Suivi de la Normalisation')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdr',
            name='service',
            field=models.CharField(choices=[('SAG', 'Affaires Generales'), ('SMGCM', 'Mines Géologie et Cadastre Minier'), ('BRCAM', 'Brigade de Contôle des Activités Minières'), ('SIDTPI', 'Industrie et Developpement Technologique et Propriété Industrielle')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='courier',
            name='types',
            field=models.CharField(choices=[('D', 'Depart'), ('A', 'Arrive')], max_length=10),
        ),
    ]
