# Generated by Django 3.1.6 on 2021-04-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210401_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('actualite', 'Actualite'), ('magazine', 'Magzi'), ('annouce', 'Anor'), ('mines', 'Mines'), ('industries', 'Industries'), ('développement_Technologique', 'Developpement Technologique'), ('blog_Post', 'Blog Post'), ('inspections', 'Inspections')], default='actualite', max_length=50),
        ),
    ]
