# Generated by Django 3.1.6 on 2021-04-06 10:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210402_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('actualite', 'Actualite'), ('magazine', 'Magzi'), ('annouce', 'Anor'), ('mines', 'Mines'), ('industries', 'Industries'), ('développement_Technologique', 'Developpement Technologique'), ('blog_Post', 'Blog Post'), ('inspections', 'Inspections'), ('projet', 'Projet')], default='actualite', max_length=50),
        ),
    ]
